import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-white text-midnightblue p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-sm text-gray-600 mb-6">
          Last updated: April 24, 2025
        </p>
        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <div className="my-8">
          <h2 className="text-2xl font-bold">Interpretation and Definitions</h2>

          <div>
            <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </div>

          <div>
            <h3 className="text-xl font-semibold mb-2">Definitions</h3>
            <p className="mb-2">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>
                <strong>Account</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is
                controlled by or is under common control with a party, where
                "control" means ownership of 50% or more of the shares, equity
                interest or other securities entitled to vote for election of
                directors or other managing authority.
              </li>
              <li>
                <strong>Company</strong> (referred to as either "the Company",
                "We", "Us" or "Our" in this Agreement) refers to SRQ Yacht
                Management, LLC, 6075 Worsham Lane, Suite 102 Lakewood Ranch, FL
                34211.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on Your
                computer, mobile device or any other device by a website,
                containing the details of Your browsing history on that website
                among its many uses.
              </li>
              <li>
                <strong>Country</strong> refers to: Florida, United States
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Website.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal
                person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the
                Company to facilitate the Service, to provide the Service on
                behalf of the Company, to perform services related to the
                Service or to assist the Company in analyzing how the Service is
                used.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit).
              </li>
              <li>
                <strong>Website</strong> refers to Kokomo Yacht Club, accessible
                from{" "}
                <a
                  href="https://kokomoyachtclub.vip"
                  className="text-blue-700 hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://kokomoyachtclub.vip
                </a>
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the
                Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>
          </div>

          <div className="my-8">
            <h2 className="text-2xl font-bold">
              Collecting and Using Your Personal Data
            </h2>

            <div>
              <h3 className="text-xl font-semibold">Types of Data Collected</h3>

              <h4 className="text-lg font-medium mt-4">Personal Data</h4>
              <p>
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information may
                include, but is not limited to:
              </p>
              <ul className="list-disc list-inside space-y-1 mt-2">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
              </ul>

              <h4 className="text-lg font-medium mt-6">Usage Data</h4>
              <p>
                Usage Data is collected automatically when using the Service. It
                may include information such as Your Device's IP address,
                browser type/version, pages visited, time and date of visit,
                time spent on pages, unique device identifiers, and other
                diagnostic data.
              </p>
              <p className="mt-2">
                When You access the Service by or through a mobile device, we
                may also collect info like device type, unique ID, IP, OS,
                browser type, and other diagnostic data. We may also collect
                data your browser sends during access.
              </p>

              <h4 className="text-lg font-medium mt-6">
                Tracking Technologies and Cookies
              </h4>
              <p>
                We use Cookies and similar technologies (like beacons, tags,
                scripts) to track activity and store certain information. These
                include:
              </p>
              <ul className="list-disc list-inside space-y-2 mt-2">
                <li>
                  <strong>Cookies or Browser Cookies:</strong> Small files
                  stored on your device. You can refuse them via browser
                  settings, but some parts of the Service may not work.
                </li>
                <li>
                  <strong>Web Beacons:</strong> Small electronic files in emails
                  and webpages used to count users or verify server integrity.
                </li>
              </ul>

              <p className="mt-4">
                Cookies can be "Persistent" (stay after you go offline) or
                "Session" (deleted when browser closes). We use both:
              </p>

              <ul className="list-disc list-inside space-y-2 mt-2">
                <li>
                  <strong>Necessary / Essential Cookies</strong>
                  <br />
                  <span className="block pl-4">
                    <em>Type:</em> Session Cookies
                    <br />
                    <em>Administered by:</em> Us
                    <br />
                    <em>Purpose:</em> Allow use of core services, prevent fraud,
                    and authenticate users.
                  </span>
                </li>
                <li>
                  <strong>Cookies Policy / Notice Acceptance Cookies</strong>
                  <br />
                  <span className="block pl-4">
                    <em>Type:</em> Persistent Cookies
                    <br />
                    <em>Administered by:</em> Us
                    <br />
                    <em>Purpose:</em> Remember user consent regarding cookie
                    usage.
                  </span>
                </li>
                <li>
                  <strong>Functionality Cookies</strong>
                  <br />
                  <span className="block pl-4">
                    <em>Type:</em> Persistent Cookies
                    <br />
                    <em>Administered by:</em> Us
                    <br />
                    <em>Purpose:</em> Remember choices like login or language
                    for a more personal experience.
                  </span>
                </li>
              </ul>

              <p className="mt-4">
                For more information, see our Cookies Policy or the Cookies
                section of this Privacy Policy.
              </p>
            </div>
          </div>

          <div className="my-8">
            <h2 className="text-2xl font-bold">Use of Your Personal Data</h2>

            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>
                <strong>To provide and maintain our Service:</strong> Including
                monitoring usage.
              </li>
              <li>
                <strong>To manage Your Account:</strong> Enabling access to
                functionalities as a registered user.
              </li>
              <li>
                <strong>For the performance of a contract:</strong> Handling any
                contracts or purchases made through the Service.
              </li>
              <li>
                <strong>To contact You:</strong> Via email, calls, SMS, or app
                notifications about updates and services.
              </li>
              <li>
                <strong>To provide promotional content:</strong> News, offers,
                or info related to services unless opted out.
              </li>
              <li>
                <strong>To manage Your requests:</strong> Handling and
                responding to your communications.
              </li>
              <li>
                <strong>For business transfers:</strong> In case of merger,
                acquisition, or asset sale.
              </li>
              <li>
                <strong>For other purposes:</strong> Like analytics, trend
                spotting, campaign effectiveness, and experience improvement.
              </li>
            </ul>

            <h3 className="text-xl font-semibold mt-8">
              We may share Your personal information in the following
              situations:
            </h3>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li>
                <strong>With Service Providers:</strong> For monitoring and
                communications.
              </li>
              <li>
                <strong>For business transfers:</strong> During or in
                negotiation of company-related sales or changes.
              </li>
              <li>
                <strong>With Affiliates:</strong> Including parent and
                subsidiary companies under the same control.
              </li>
              <li>
                <strong>With Business Partners:</strong> To offer specific
                products, services, or deals.
              </li>
              <li>
                <strong>With other users:</strong> When you interact publicly
                within the Service.
              </li>
              <li>
                <strong>With Your consent:</strong> For any other purpose
                explicitly approved by you.
              </li>
            </ul>
          </div>

          <div className="my-8">
            <h2 className="text-2xl font-bold">
              Retention of Your Personal Data
            </h2>
            <p>
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use Your Personal Data as needed to:
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li>Comply with legal obligations (e.g., required by law).</li>
              <li>Resolve disputes.</li>
              <li>Enforce our legal agreements and policies.</li>
            </ul>
            <p className="mt-2">
              Usage Data is retained for a shorter duration unless:
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li>
                It's used to enhance security or improve Service functionality.
              </li>
              <li>We're legally required to retain it for longer periods.</li>
            </ul>
          </div>

          <div className="my-8">
            <h2 className="text-2xl font-bold">Delete Your Personal Data</h2>
            <p>
              You have the right to delete or request our help in deleting the
              Personal Data we’ve collected about you.
            </p>
            <p>
              Our Service may allow you to delete certain personal information
              directly from within your account settings.
            </p>
            <p>
              You can update, amend, or delete your information anytime by
              logging into your Account and visiting the settings section. You
              may also contact us for access to, correction of, or deletion of
              any information you provided.
            </p>
            <p>
              Please note that we may retain some information when required by
              law or when we have a legitimate legal reason to do so.
            </p>
          </div>

          <div className="my-8">
            <section>
              <h2 className="text-2xl font-bold">
                Disclosure of Your Personal Data
              </h2>
              <h3 className="text-xl font-semibold mt-4">
                Business Transactions
              </h3>
              <p>
                If the Company is involved in a merger, acquisition, or asset
                sale, your personal data may be transferred. You will be
                notified before your data becomes subject to a different Privacy
                Policy.
              </p>
              <h3 className="text-xl font-semibold mt-4">Law Enforcement</h3>
              <p>
                We may disclose your personal data when required by law or in
                response to valid requests by public authorities.
              </p>
              <h3 className="text-xl font-semibold mt-4">
                Other Legal Requirements
              </h3>
              <p>The Company may disclose your data in good faith to:</p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Comply with legal obligations</li>
                <li>Protect and defend our rights or property</li>
                <li>Investigate possible misconduct related to the Service</li>
                <li>Protect the safety of users or the public</li>
                <li>Protect against legal liability</li>
              </ul>
            </section>

            <section>
              <h3 className="text-xl mt-4 font-bold">
                Security of Your Personal Data
              </h3>
              <p>
                We take data security seriously, but no internet or storage
                method is 100% secure. While we try to use commercially
                acceptable means to protect your Personal Data, we cannot
                guarantee its absolute security.
              </p>
            </section>

            <section>
              <h3 className="text-xl mt-4 font-bold">Children's Privacy</h3>
              <p>
                Our Service is not intended for anyone under the age of 13. We
                do not knowingly collect personal data from children. If you are
                a parent and become aware that your child has provided us
                personal data, please contact us.
              </p>
              <p>
                If we confirm that we’ve collected data from a child under 13
                without parental consent, we will delete it promptly. In some
                countries, we may need parental consent to process personal
                data.
              </p>
            </section>
          </div>

          <div className="my-8">
            <h1 className="text-2xl font-bold">
              Telephone Consumer Protection Act (47 U.S.C. § 227)
            </h1>

            <section className="space-y-4 mt-4">
              <h2 className="text-xl font-semibold">Links to Other Websites</h2>
              <p>
                Our Service may contain links to other websites that are not
                operated by Us. If You click on a third party link, You will be
                directed to that third party's site. We strongly advise You to
                review the Privacy Policy of every site You visit.
              </p>
              <p>
                We have no control over and assume no responsibility for the
                content, privacy policies or practices of any third party sites
                or services.
              </p>
            </section>

            <section className="space-y-4 mt-4">
              <h2 className="text-xl font-semibold">Summary</h2>
              <p>
                This summary of the Telephone Consumer Protection Act (47 U.S.C.
                § 227) is provided for convenience only. Individuals should also
                refer to the United States Code at{" "}
                <a
                  className="text-blue-600 underline"
                  href="http://www.gpoaccess.gov"
                >
                  http://www.gpoaccess.gov
                </a>
                .
              </p>
            </section>

            <section className="space-y-4 mt-4">
              <h2 className="text-xl font-semibold">Definitions</h2>
              <ol className="list-decimal pl-6 space-y-2">
                <li>
                  "Automatic telephone dialing system" means equipment which has
                  the capacity:
                  <ul className="list-disc pl-6">
                    <li>
                      to store or produce telephone numbers to be called, using
                      a random or sequential number generator; and
                    </li>
                    <li>to dial such numbers.</li>
                  </ul>
                </li>
                <li>
                  "Established business relationship" as per section 64.1200 of
                  title 47, Code of Federal Regulations (as of Jan 1, 2003),
                  also includes relationships with business subscribers under
                  the same terms as residential.
                </li>
                <li>
                  "Telephone facsimile machine" means equipment capable of:
                  <ul className="list-disc pl-6">
                    <li>
                      transcribing text/images from paper to an electronic
                      signal to transmit over a telephone line, or
                    </li>
                    <li>
                      receiving an electronic signal over a phone line and
                      transcribing it onto paper.
                    </li>
                  </ul>
                </li>
                <li>
                  "Telephone solicitation" refers to calls/messages to promote
                  goods/services, excluding calls:
                  <ul className="list-disc pl-6">
                    <li>with prior express consent,</li>
                    <li>
                      to individuals with an established business relationship,
                      or
                    </li>
                    <li>by a tax-exempt nonprofit organization.</li>
                  </ul>
                </li>
                <li>
                  "Unsolicited advertisement" refers to any promotional material
                  sent without the recipient's prior consent.
                </li>
              </ol>
            </section>

            {/* More Sections */}
            <section className="space-y-4 mt-4">
              <h2 className="text-xl font-semibold">
                Restrictions on Use of Automated Telephone Equipment
              </h2>
              <p className="font-semibold">Prohibitions (b)(1):</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>
                  No auto-dialed or prerecorded calls to emergency lines or
                  hospitals, or to any service the recipient is charged for.
                </li>
                <li>
                  No artificial/prerecorded messages to residential lines
                  without prior express consent (except emergencies).
                </li>
                <li>No unsolicited faxes unless within exceptions stated.</li>
                <li>
                  No autodialers tying up multiple business lines
                  simultaneously.
                </li>
              </ul>
              <p className="font-semibold">Regulations (b)(2):</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>
                  FCC shall create regulations, allow businesses to opt-out of
                  robocalls, exempt non-commercial messages, etc.
                </li>
                <li>
                  Fax senders must provide clear opt-out info, contact details,
                  and mechanisms for opt-out.
                </li>
                <li>
                  Exemptions for tax-exempt nonprofits and small businesses are
                  available under certain conditions.
                </li>
              </ul>
              <p className="font-semibold">Private Right of Action (b)(3):</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>
                  Individuals can sue for actual damages or $500 per violation,
                  whichever is greater.
                </li>
                <li>
                  Damages can be tripled if the violation is willful or knowing.
                </li>
              </ul>
            </section>

            <section className="space-y-4 mt-4">
              <h2 className="text-xl font-semibold">
                Privacy Rights & National Do Not Call List
              </h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>
                  FCC required to create rules to protect residential users from
                  unwanted calls.
                </li>
                <li>
                  Implementation of a national database (Do Not Call Registry).
                </li>
                <li>
                  Carriers must inform customers of their right to opt out.
                </li>
                <li>
                  Telemarketers must access this list and avoid calling
                  registered numbers.
                </li>
                <li>States may not override the national database.</li>
                <li>Penalties for violations and consumer rights to sue.</li>
              </ul>
            </section>

            <section className="space-y-4 mt-4">
              <h2 className="text-xl font-semibold">
                Enforcement and State Involvement
              </h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>States can sue violators on behalf of residents.</li>
                <li>Federal courts have exclusive jurisdiction.</li>
                <li>States must notify FCC before filing.</li>
                <li>
                  States can use their own legal powers for investigation.
                </li>
              </ul>
            </section>

            <section className="space-y-4 mt-4">
              <h2 className="text-xl font-semibold">
                Technical & Procedural Standards
              </h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>
                  Fax transmissions must include sender identity, date/time, and
                  phone number.
                </li>
                <li>
                  Voice systems must identify the caller at the beginning and
                  allow line release within 5 seconds of hang-up.
                </li>
              </ul>
            </section>

            <section className="space-y-4 mt-4">
              <h2 className="text-xl font-semibold">
                Annual Junk Fax Enforcement Report
              </h2>
              <p>
                The FCC must submit yearly reports to Congress detailing
                complaints, enforcement actions, penalties, and recovery of
                penalties related to junk faxes.
              </p>
            </section>

            <footer className="mt-10 text-sm text-gray-600">
              <p>
                This summary of the Telephone Consumer Protection Act (47 U.S.C.
                § 227) is provided for convenience only. For the official
                source, visit{" "}
                <a
                  className="text-blue-600 underline"
                  href="http://www.gpoaccess.gov"
                >
                  gpoaccess.gov
                </a>
                .
              </p>
            </footer>
          </div>

          <div className="my-8">
            <section>
              <h2 className="text-xl font-bold mb-4">
                Changes to this Privacy Policy
              </h2>
              <p className="mb-4">
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page.
              </p>
              <p className="mb-4">
                We will let you know via email and/or a prominent notice on our
                Service prior to the change becoming effective and update the
                "Last updated" date at the top of this Privacy Policy.
              </p>
              <p>
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>
            </section>
          </div>

          <div className="my-8">
            <section>
              <h2 className="text-xl font-bold mb-4">Contact Us</h2>
              <p className="mb-4">
                If you have any questions about this Privacy Policy, You can
                contact us:
              </p>
              <ul className="list-disc list-inside space-y-2">
                <li>
                  By email:{" "}
                  <a
                    href="mailto:brian@kokomoyachtclub.vip"
                    className="text-blue-600 underline"
                  >
                    brian@kokomoyachtclub.vip
                  </a>
                </li>
                <li>
                  By visiting this page on our website:{" "}
                  <a
                    href="https://kokomoyachtclub.vip/contact"
                    className="text-blue-600 underline"
                  >
                    kokomoyachtclub.vip/contact
                  </a>
                </li>
                <li>
                  By phone number:{" "}
                  <span className="text-gray-700">(941) 259-2248</span>
                </li>
              </ul>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
